name: colegio_abogados_app
description: "Aplicación móvil del Colegio de Abogados de Quilmes"
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ^3.7.2
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias de red optimizadas
  http: ^1.2.0
  connectivity_plus: ^5.0.2
  
  # UI y navegación optimizada
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.6.0
  
  # WebView solo si es absolutamente necesario (comentado para mejor rendimiento)
  # webview_flutter: ^4.4.4
  
  # Información del dispositivo y app
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  
  # Opcional: para compartir diagnóstico
  # share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# Configuraciones de optimización
flutter:
  uses-material-design: true
  
  # Configuración optimizada de assets (descomenta si tienes assets)
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Configuración de fuentes (opcional para mejor tipografía)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700